---

- hosts: all
  become: yes
  vars:

    # project name, by default derived from parent folder, e.g. php-starter-pack
    project_name: "{{ playbook_dir | dirname | basename }}"

    # linux user who will own project files, defaults to ansible SSH user
    user_name: "{{ ansible_ssh_user | default(ansible_env.SUDO_USER, true) | default(ansible_env.USER, true) | default(ansible_user_id) }}"

    # linux user's home folder, e.g. /home/ubuntu
    home_path: "/home/{{ user_name }}"

    # project path, defaults to being in user's home folder, e.g. /home/ubuntu/project
    project_path: "{{ home_path }}/{{ project_name }}"

    # public web server root, e.g. /home/ubuntu/project/public
    public_path: "{{ project_path }}/public"

  pre_tasks:
    - name: Check required vars are defined
      assert:
        that:
          - project_name is defined
          - host_name is defined
          - user_name is defined

    - name: Ensure Apt and SSL are latest
      apt:
        name:
          - openssl
          - libssl-dev
          - libssl-doc
          - libffi-dev
        update_cache: yes
        state: latest

    - name: Install common server packages
      apt:
        name:
          - build-essential
          - bash-completion
          - make
          - htop
          - vim
          - unzip
          - curl
        state: present

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.mysql
    - geerlingguy.nginx
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.composer

  post_tasks:
    - name: Install composer dependencies for project
      composer:
        command: install
        working_dir: "{{ project_path }}"
        optimize_autoloader: true

    - name: Create default config file if it doesn't exist already
      template:
        src: config.php.j2
        dest: "{{ project_path }}/config.php"
        force: no

    - name: Add project database as default for linux user in .my.cnf
      lineinfile: dest={{ home_path }}/.my.cnf line='database="{{ db_name }}"'
      become: no

    - name: Output some of the important vars for reference
      debug:
        msg: "group_names: {{ group_names }}, host_name: {{ host_name }}, user_name: {{ user_name }}, db_name: {{ db_name }}"
