---

- hosts: all
  become: yes

  pre_tasks:
    - name: Ensure Apt and SSL are latest
      apt:
        name:
          - openssl
          - libssl-dev
          - libssl-doc
          - libffi-dev
        update_cache: yes
        state: latest

    - name: Install common server packages
      apt:
        name:
          - build-essential
          - bash-completion
          - make
          - htop
          - vim
          - unzip
          - curl
        state: present

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.nginx
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.composer

  post_tasks:
    # install composer dependencies for project
    - composer:
        command: install
        working_dir: "{{ project_path }}"
        optimize_autoloader: true
    - debug:
        msg: "group_names: {{ group_names }}, host_name: {{ host_name }}"
